fix: buildURL error
kuitos/axios-extensions pull request #101
Opened 2023-05-28 07:38 UTC by mengqiuleo

fix error: Missing "./lib/helpers/buildURL" export in "axios" package

2023-05-28 07:40 UTC, mengqiuleo commented
#99

2023-05-28 07:49 UTC, mengqiuleo commented
with axios 1.x, we can use axios.getUri API, https://github.com/Gerhut/axios-debug-log/commit/df0f23a8c2258c4764227ea93dcd7951a651d90a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

2023-05-28 07:50 UTC, mengqiuleo commented
When using the axios 1.x version, typescript error for `AxiosRequestConfig`, https://github.com/axios/axios/issues/5573

2023-05-28 07:53 UTC, mengqiuleo commented
All test cases have passed successfully.

2023-05-29 03:09 UTC, kuitos requested changes
Nice work~
But `axios.getUri` depends on axios 1.x, it's breaking change for who using axios 0.x, maybe we should publish a major version like 4.0 for axiso-extensions?

2023-05-29 03:09 UTC, kuitos commented on yarn.lock
yarn.lock does't need to be submitted

2023-05-29 08:05 UTC, mengqiuleo commented
> Nice work~ But `axios.getUri` depends on axios 1.x, it's breaking change for who using axios 0.x, maybe we should publish a major version like 4.0 for axiso-extensions?

@kuitos, I've tested `axios.getUri` locally, it's **compatible with axios 0.x**, and I removed the code I originally added for ts type，it's not compatible，use `@ ts-ignore`  to resolve ts type error.

2023-05-29 11:18 UTC, merged

2023-05-29 11:19 UTC, kuitos commented
Thanks for your nice work~

2024-02-24 01:58 UTC, onlywei commented
Will this ever be published to npm?

2024-06-11 09:21 UTC, botmaster commented
Please, publish this fix to npm 😔

2025-05-12 13:09 UTC, mpicardvolvo commented
This project has been abandoned, too bad